# Generated by Django 4.2.4 on 2023-08-19 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_watchlist_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='title',
            field=models.CharField(max_length=52),
        ),
    ]
